nelmio_api_doc:
    documentation:
        info:
            title: Avito API
            description: API for avito advert platform
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
